LR12/config/routes.rb
Rails.application.routes.draw do
  get 'session/login'
  post 'session/create'
  get 'session/logout'
  get '/logout', to: 'session#logout'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'input#index'
  get 'output' => 'output#output'

  get 'usersbd' => 'output#users'
end

LR12/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

LR12/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

LR12/app/controllers/application_controller.rb
# frozen_string_literal: true

# application
# :reek:IrresponsibleModule
class ApplicationController < ActionController::Base
  include SessionHelper

  before_action :require_login

  private

  def require_login
    redirect_to session_login_url unless signed_in?
  end
end

LR12/app/controllers/input_controller.rb
# frozen_string_literal: true

# Input controller
class InputController < ApplicationController
  def index; end
end

LR12/app/controllers/output_controller.rb
# frozen_string_literal: true

# Output controller
# :reek:UtilityFunction
# :reek:TooManyStatements
# :reek:UncommunicativeVariableName
# :reek:IrresponsibleModule
class OutputController < ApplicationController
  def output
    sequence = params[:sequence]
    @error = 1
    if sequence == ''
      @output = 'you did not write anything:('
    elsif sequence.to_i.zero?
      @output = 'please, enter a number'
    else
      @output = "Your initial sequence: #{sequence}"
      @error = 0
      res = find(sequence)
      subsequences_ = res[0]
      max = res[1]
      if subsequences_.length.zero?
        @subsequences = 'There are no rising subsequences'
        @error = 1
      else
        @subsequences = subsequences_
        @max = "maximum length rising subsequence: #{max}"
      end
    end
  end

  def find(sequence)
    rising_subsequences = []
    subsequence = sequence[0]
    max = ''
    count = 1
    n = 0
    (1..sequence.length).each do |i|
      curr_seq = sequence[i]
      if curr_seq.to_i > sequence[i - 1].to_i
        count += 1
        subsequence += curr_seq
      else
        if count > 1
          rising_subsequences[n] = subsequence
          max = subsequence if subsequence.length > max.length
          n += 1
        end
        count = 1
        subsequence = curr_seq
      end
    end
    [rising_subsequences, max]
  end

  def users
    respond_to do |format|
      res = User.all
      format.xml {render xml: res}
      format.json {render json: res}
    end
  end
end

LR12/app/controllers/session_controller.rb
  # frozen_string_literal: true

  # Session controller
  # :reek:TooManyStatements
  class SessionController < ApplicationController
    skip_before_action :require_login, only: %i[login create]

    def login; end

    def create
      user = User.find_by username: params[:username]

      if user&.authenticate(params[:password])
        # sign_in user
        p 'Login'
        sign_in user
        redirect_to root_url
      else
        p 'redirect'
        redirect_to session_login_url
      end
    end

    def logout
      sign_out
      redirect_to session_login_url
    end
  end

LR12/app/controllers/users_controller.rb
# frozen_string_literal: true

# Users controller
# :reek:DuplicateMethodCall
# :reek:TooManyStatements
# :reek:InstanceVariableAssumption
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: %i[new create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

LR12/app/helpers/application_helper.rb
module ApplicationHelper
  include SessionHelper
end

LR12/app/helpers/input_helper.rb
module InputHelper
end

LR12/app/helpers/output_helper.rb
module OutputHelper
end

LR12/app/helpers/session_helper.rb
module SessionHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 10.days }
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id]) # "если current_user на данном этапе nil, то нужно выполнить...
    # иначе - "
  end
end

LR12/app/helpers/users_helper.rb
module UsersHelper
end

LR12/app/views/input/index.html.erb
<h2>Input</h2>
<hr>
<%= form_tag("/output", :method => "get") do %>
    <%= text_field_tag(:sequence) %>
    <%= submit_tag("Определить наиболее длинную монотонно возрастающую последовательность") %>
<% end %>
<hr>
<%= link_to 'Users', '/users' %>
<hr>
<%= link_to 'log out', '/logout' %>

LR12/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LR8</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

LR12/app/views/output/output.html.erb
<h2>Output</h2>
<hr>
  <%= @output %>
  <hr>

<% if @subsequences.is_a?(String) %>
  <%= @subsequences %>
<% end %>

<% if @error == 0 %>
  <table>
    <% @subsequences.each_with_index do |sequence, index| %>
      <tr>
        <td><%= index %>:</td>
        <td><%= sequence %></td>
      </tr>
    <% end %>
  </table>

  <hr>

  <%= @max %>
<% end %>

<%= link_to 'Назад', :back %>

LR12/app/views/session/login.html.erb
<h1>Session#login</h1>
<p>Find me in app/views/session/login.html.erb</p>
<%= form_with url: session_create_url, method: :post, local:true do |f| %>
  <%= f.text_field :username, required: true, label: 'username' %>
  <%= f.password_field :password, required: true, label: 'password' %>
  <%= f.submit 'log in' %>
<% end %>

<%= link_to 'sign up', new_user_path %>

LR12/app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>

LR12/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

LR12/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

LR12/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<hr>
<%= link_to 'START CALCULATING', root_url(@user) %>

LR12/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', session_login_url %>

LR12/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Last login at:</strong>
  <%= @user.last_login_at %>
</p>
<hr>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<hr>
<%= link_to 'START CALCULATING', root_url(@user) %>